CLASS cl_ptf_variant_manager DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC
  FOR BEHAVIOR OF p_ptf_variant.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS CL_PTF_VARIANT_MANAGER IMPLEMENTATION.
ENDCLASS.
