CLASS cl_ptf_variant_tag_manager DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.

    TYPES: string_table          TYPE STANDARD TABLE OF string WITH DEFAULT KEY,
           ptf_simple_tags       TYPE STANDARD TABLE OF ptf_variant_tag WITH DEFAULT KEY,
           ptf_var_tag_map_table TYPE STANDARD TABLE OF ptf_var_tag_map WITH DEFAULT KEY,
           ptf_tags              TYPE STANDARD TABLE OF ptf_var_tag WITH DEFAULT KEY,
           ptf_tag_texts         TYPE STANDARD TABLE OF ptf_var_tagt WITH DEFAULT KEY,
           ptf_variants          TYPE STANDARD TABLE OF ptf_var_tag_map WITH DEFAULT KEY,
           ptf_vtags             TYPE STANDARD TABLE OF v_ptf_var_tag WITH DEFAULT KEY,
           tag_inputs            TYPE STANDARD TABLE OF ptf_variant_tag_input WITH DEFAULT KEY,
           variants              TYPE STANDARD TABLE OF ptf_varname WITH DEFAULT KEY.

    CLASS-METHODS:

      remove_tags_for_variants
        IMPORTING
          variants TYPE variants
          tags     TYPE ptf_simple_tags,

      add_tags_for_variants
        IMPORTING
          variants TYPE variants
          tags     TYPE ptf_simple_tags,

      update_tags_by_var_and_user
        IMPORTING user                TYPE sy-uname
                  varname             TYPE ptf_varname
        CHANGING  tags                TYPE tag_inputs
        RETURNING VALUE(updated_maps) TYPE ptf_var_tag_map_table,

      get_tags_for_variant_and_user
        IMPORTING user        TYPE sy-uname
                  variant     TYPE ptf_varname
        RETURNING VALUE(tags) TYPE tag_inputs,

      transport_ptf_variant_tags
        IMPORTING ptf_var_tags                TYPE ptf_tags
                  ptf_var_tag_texts           TYPE ptf_tag_texts
                  deleted_var_tag_map_entries TYPE ptf_var_tag_map_table,

      transport_ptf_var_tag_maps
        IMPORTING ptf_var_tag_maps TYPE ptf_var_tag_map_table,

      read_tagged_variants_for_user
        IMPORTING user          TYPE sy-uname
        RETURNING VALUE(result) TYPE ptf_var_tag_map_table,

      set_autogenerated_data_for_tag
        IMPORTING date        TYPE sy-datum
                  user        TYPE sy-uname
        CHANGING  ptf_var_tag TYPE v_ptf_var_tag,

      get_variant_for_tags
        IMPORTING tags            TYPE ptf_simple_tags
                  user            TYPE sy-uname
        RETURNING VALUE(variants) TYPE ptf_variants,

      is_admin
        IMPORTING user              TYPE sy-uname
        RETURNING VALUE(is_allowed) TYPE abap_bool,

      get_editable_tags_for_user
        IMPORTING user        TYPE sy-uname
                  language    TYPE sy-langu
        RETURNING VALUE(tags) TYPE ptf_vtags,

      delete_maps_for_tags
        IMPORTING tags TYPE ptf_tags,

      delete_tags_for_variant
        IMPORTING variant TYPE ptf_varname.

  PROTECTED SECTION.
  PRIVATE SECTION.

    CONSTANTS: c_visibility_public TYPE String VALUE 'PUBLIC',
               c_user_prefix       TYPE String VALUE '_SAP',
               c_user_regex        TYPE string VALUE '_SAP.*',
               c_admin_regex       TYPE String VALUE '_SAPD021185|_SAPD040401|_SAPD049099|_SAPD072204'.



    CLASS-DATA: pers_number_dao TYPE REF TO lif_pers_number_retrieval_dao,
                transport_dao   TYPE REF TO lif_transport_manager_dao.


    CLASS-METHODS: convert_user_name
      IMPORTING user                       TYPE sy-uname
      RETURNING VALUE(converted_user_name) TYPE uname.

ENDCLASS.



CLASS CL_PTF_VARIANT_TAG_MANAGER IMPLEMENTATION.


  METHOD add_tags_for_variants.
    DATA: map_tag          TYPE ptf_var_tag_map,
          map_tag_2_insert TYPE STANDARD TABLE OF ptf_var_tag_map WITH DEFAULT KEY,
          map_tag_db       TYPE STANDARD TABLE OF ptf_var_tag_map WITH DEFAULT KEY,
          ranged_tags      TYPE RANGE OF ptf_variant_tag.

    LOOP AT tags ASSIGNING FIELD-SYMBOL(<tag_2_search>).
      APPEND VALUE #( sign   = 'I' option = 'EQ' low = <tag_2_search> high = ''   ) TO ranged_tags.
    ENDLOOP.

    SELECT * FROM ptf_var_tag_map WHERE tag IN @ranged_tags INTO TABLE @map_tag_db.

    LOOP AT variants ASSIGNING FIELD-SYMBOL(<variant>).
      LOOP AT tags ASSIGNING FIELD-SYMBOL(<tag>).
        CLEAR map_tag.
        map_tag-mandt = sy-mandt.
        map_tag-tag = <tag>.
        map_tag-varname = <variant>.

        TRY.
            DATA(entry) = map_tag_db[ tag = <tag> ].
          CATCH cx_root.
            APPEND map_tag TO map_tag_2_insert.
        ENDTRY.

      ENDLOOP.
    ENDLOOP.

    INSERT ptf_var_tag_map FROM TABLE map_tag_2_insert.

    cl_ptf_variant_tag_manager=>transport_ptf_var_tag_maps( ptf_var_tag_maps = map_tag_2_insert ).

  ENDMETHOD.


  METHOD convert_user_name.

    IF cl_ptf_variant_tag_manager=>pers_number_dao IS INITIAL.
      cl_ptf_variant_tag_manager=>pers_number_dao = NEW lcl_pers_num_dao_impl( ).
    ENDIF.
    converted_user_name = cl_ptf_variant_tag_manager=>pers_number_dao->retrieve_pers_number( user = user ).

    IF converted_user_name IS INITIAL.
      converted_user_name = user.
    ENDIF.
    converted_user_name = |{ c_user_prefix }{ converted_user_name }|.

  ENDMETHOD.


  METHOD delete_maps_for_tags.
    DATA: ranged_tags TYPE RANGE OF ptf_variant_tag.

    IF tags IS INITIAL.

      RETURN.

    ELSE.

      LOOP AT tags ASSIGNING FIELD-SYMBOL(<tag>).
        APPEND VALUE #( sign   = 'I' option = 'EQ' low = <tag> high = ''  ) TO ranged_tags.
      ENDLOOP.

      DELETE FROM ptf_var_tag_map WHERE tag IN ranged_tags.

    ENDIF.

  ENDMETHOD.


  METHOD delete_tags_for_variant.
    DELETE FROM ptf_var_tag_map WHERE varname = @variant.
  ENDMETHOD.


  METHOD get_editable_tags_for_user.

    IF NOT matches( val = user regex = c_user_regex ).
      DATA(converted_user_name) = cl_ptf_variant_tag_manager=>convert_user_name( user = user ).
    ELSE.
      converted_user_name = user.
    ENDIF.

    SELECT ptf_var_tag~tag, ptf_var_tag~visibility, ptf_var_tagt~text, ptf_var_tag~creationdat, ptf_var_tag~creator
    FROM ptf_var_tag LEFT OUTER JOIN ptf_var_tagt ON ptf_var_tag~tag = ptf_var_tagt~tag AND ptf_var_tagt~langu = @language
    WHERE ( ptf_var_tag~creator = @converted_user_name OR ptf_var_tag~visibility = @c_visibility_public )
      ORDER BY ptf_var_tag~tag ASCENDING
    INTO TABLE @DATA(ptf_var_tags_with_description).

    MOVE-CORRESPONDING ptf_var_tags_with_description TO tags.

  ENDMETHOD.


  METHOD get_tags_for_variant_and_user.

    IF NOT matches( val = user regex = c_user_regex ).
      DATA(converted_user_name) = cl_ptf_variant_tag_manager=>convert_user_name( user = user ).
    ELSE.
      converted_user_name = user.
    ENDIF.

    SELECT ptf_var_tag~tag FROM ptf_var_tag
      LEFT OUTER JOIN ptf_var_tag_map ON ptf_var_tag~tag = ptf_var_tag_map~tag
      WHERE ptf_var_tag_map~varname = @variant
      AND ( ptf_var_tag~visibility = @c_visibility_public OR ptf_var_tag~creator = @converted_user_name )
      ORDER BY ptf_var_tag~tag ASCENDING
      INTO CORRESPONDING FIELDS OF TABLE @tags.

  ENDMETHOD.


  METHOD get_variant_for_tags.

    DATA ranged_tags TYPE RANGE OF ptf_variant_tag.

    IF NOT matches( val = user regex = c_user_regex ).
      DATA(converted_user) = cl_ptf_variant_tag_manager=>convert_user_name( user = user ).
    ELSE.
      converted_user = user.
    ENDIF.

    LOOP AT tags ASSIGNING FIELD-SYMBOL(<tag>).
      APPEND VALUE #( sign   = 'I' option = 'EQ' low = <tag> high = ''  ) TO ranged_tags.
    ENDLOOP.

    SELECT ptf_var_tag_map~mandt, ptf_var_tag_map~tag, ptf_var_tag_map~varname FROM ptf_var_tag_map
    LEFT OUTER JOIN ptf_var_tag ON ptf_var_tag~tag = ptf_var_tag_map~tag
      WHERE ptf_var_tag~tag IN @ranged_tags
        AND ( ptf_var_tag~visibility = @c_visibility_public
                OR ptf_var_tag~creator = @converted_user
      )
      ORDER BY ptf_var_taG_map~varname ASCENDING
       INTO TABLE @variants.

  ENDMETHOD.


  METHOD is_admin.

    IF NOT matches( val = user regex = c_user_regex ).
      DATA(converted_user_name) = cl_ptf_variant_tag_manager=>convert_user_name( user = user ).
    ELSE.
      converted_user_name = user.
    ENDIF.

    IF matches( val = converted_user_name regex = c_admin_regex ).
      is_allowed = abap_true.
    ELSE.
      is_allowed = abap_false.
    ENDIF.

  ENDMETHOD.


  METHOD read_tagged_variants_for_user.

    IF NOT matches( val = user regex = c_user_regex ).
      DATA(converted_user_name) = cl_ptf_variant_tag_manager=>convert_user_name( user = user ).
    ELSE.
      converted_user_name = user.
    ENDIF.


    SELECT ptf_var_tag_map~* FROM ptf_var_tag_map
      LEFT OUTER JOIN ptf_var_tag ON ptf_var_tag~tag = ptf_var_tag_map~tag
      WHERE ptf_var_tag~visibility = @c_visibility_public
      OR ptf_var_tag~creator = @converted_user_name
      ORDER BY ptf_var_tag_map~tag, ptf_var_tag_map~varname ASCENDING
      INTO TABLE @result.

  ENDMETHOD.


  METHOD remove_tags_for_variants.
    DATA: map_tag          TYPE ptf_var_tag_map,
          map_tag_2_delete TYPE STANDARD TABLE OF ptf_var_tag_map WITH DEFAULT KEY.


    LOOP AT variants ASSIGNING FIELD-SYMBOL(<variant>).
      LOOP AT tags ASSIGNING FIELD-SYMBOL(<tag>).
        CLEAR map_tag.
        map_tag-mandt = sy-mandt.
        map_tag-tag = <tag>.
        map_tag-varname = <variant>.
        APPEND map_tag TO map_tag_2_delete.
      ENDLOOP.
    ENDLOOP.

    DELETE ptf_var_tag_map FROM TABLE map_tag_2_delete.

    cl_ptf_variant_tag_manager=>transport_ptf_var_tag_maps( ptf_var_tag_maps = map_tag_2_delete ).
  ENDMETHOD.


  METHOD set_autogenerated_data_for_tag.

    ptf_var_tag-creationdat = date.

    IF NOT matches( val = user regex = c_user_regex ).
      DATA(converted_user_name) = cl_ptf_variant_tag_manager=>convert_user_name( user = user ).
    ELSE.
      converted_user_name = user.
    ENDIF.

    ptf_var_tag-creator = converted_user_name.

  ENDMETHOD.


  METHOD transport_ptf_variant_tags.

    DATA: e071k TYPE lif_transport_manager_dao=>tt_e071k,
          ko200 TYPE lif_transport_manager_dao=>tt_ko200.

   DATA(lo_util) = new cl_ptf_variant( ).

    LOOP AT ptf_var_tags ASSIGNING FIELD-SYMBOL(<ptf_var_tag>).
      IF NOT lo_util->is_in_customer_namespace( iv_tag = <ptf_var_tag>-tag ).
        DATA(key_var_tag) = |{ <ptf_var_tag>-mandt WIDTH = 3 }{ <ptf_var_tag>-tag WIDTH = 80 }|.
        APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' objname = 'PTF_VAR_TAG' tabkey = key_var_tag mastertype = 'TABU' mastername = 'PTF_VAR_TAG' lang = sy-langu ) TO e071k.
        APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' obj_name = 'PTF_VAR_TAG' objfunc = 'K' lang = sy-langu ) TO ko200.
      ENDIF.
    ENDLOOP.

    LOOP AT ptf_var_tag_texts ASSIGNING FIELD-SYMBOL(<ptf_var_tagt>).
      IF NOT lo_util->is_in_customer_namespace( iv_tag = <ptf_var_tagt>-tag ).
        DATA(key_var_tagt) = |{ <ptf_var_tagt>-mandt WIDTH = 3 }{ <ptf_var_tagt>-langu WIDTH = 1 }{ <ptf_var_tagt>-tag WIDTH = 80 }|.
        APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' objname = 'PTF_VAR_TAGT' tabkey = key_var_tagt mastertype = 'TABU' mastername = 'PTF_VAR_TAGT' lang = sy-langu ) TO e071k.
        APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' obj_name = 'PTF_VAR_TAGT' objfunc = 'K' lang = sy-langu ) TO ko200.
      ENDIF.
    ENDLOOP.

    LOOP AT deleted_var_tag_map_entries ASSIGNING FIELD-SYMBOL(<deleted_map_entry>).
      IF NOT lo_util->is_in_customer_namespace( iv_tag = <deleted_map_entry>-tag iv_varname = <deleted_map_entry>-varname ).
        DATA(key_map_tag) = |{ <deleted_map_entry>-mandt WIDTH = 3 }{ <deleted_map_entry>-tag WIDTH = 80 }{ <deleted_map_entry>-varname WIDTH = 31 }|.
        APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' objname = 'PTF_VAR_TAG_MAP' tabkey = key_map_tag mastertype = 'TABU' mastername = 'PTF_VAR_TAG_MAP' lang = sy-langu ) TO e071k.
        APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' obj_name = 'PTF_VAR_TAG_MAP' objfunc = 'K' lang = sy-langu ) TO ko200.
      ENDIF.
    ENDLOOP.

    IF e071k IS NOT INITIAL AND ko200 IS NOT INITIAL.

      IF cl_ptf_variant_tag_manager=>transport_dao IS INITIAL.
        cl_ptf_variant_tag_manager=>transport_dao = NEW lcl_trans_mgr_dao_impl( ).
      ENDIF.

      cl_ptf_variant_tag_manager=>transport_dao->transport(
        CHANGING
          ko200 = ko200
          e071k = e071k
      ).

    ENDIF.

  ENDMETHOD.


  METHOD transport_ptf_var_tag_maps.

    DATA: e071k TYPE lif_transport_manager_dao=>tt_e071k,
          ko200 TYPE lif_transport_manager_dao=>tt_ko200.
    DATA(lo_util) = NEW cl_ptf_variant( ).

    LOOP AT ptf_var_tag_maps ASSIGNING FIELD-SYMBOL(<tag_map_entry>).
      IF NOT lo_util->is_in_customer_namespace( iv_tag = <tag_map_entry>-tag iv_varname = <tag_map_entry>-varname ).
        DATA(key_map_tag) = |{ <tag_map_entry>-mandt WIDTH = 3 }{ <tag_map_entry>-tag WIDTH = 80 }{ <tag_map_entry>-varname WIDTH = 31 }|.
        APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' objname = 'PTF_VAR_TAG_MAP'  mastertype = 'TABU' mastername = 'PTF_VAR_TAG_MAP' tabkey = key_map_tag  lang = sy-langu ) TO e071k.
        APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' obj_name = 'PTF_VAR_TAG_MAP' objfunc = 'K' lang = sy-langu ) TO ko200.
      ENDIF.
    ENDLOOP.

    IF e071k IS NOT INITIAL AND ko200 IS NOT INITIAL.

      IF cl_ptf_variant_tag_manager=>transport_dao IS INITIAL.
        cl_ptf_variant_tag_manager=>transport_dao = NEW lcl_trans_mgr_dao_impl( ).
      ENDIF.

      cl_ptf_variant_tag_manager=>transport_dao->transport(
        CHANGING
          ko200 = ko200
          e071k = e071k
      ).

    ENDIF.

  ENDMETHOD.


  METHOD update_tags_by_var_and_user.

    DATA ranged_actual_user_tags TYPE RANGE OF ptf_variant_tag.

    "only called below Form Update (after deletion of old script version including Tag assignment was done). Retrieval here needed at all?
    DATA(actual_user_tags) = cl_ptf_variant_tag_manager=>get_tags_for_variant_and_user(
      EXPORTING
        user    = user
        variant = varname
    ).

    SORT tags BY tag ASCENDING.

    IF tags NE actual_user_tags.

      LOOP AT actual_user_tags ASSIGNING FIELD-SYMBOL(<act_user_tag>).
        APPEND VALUE #( sign = 'I' option = 'EQ' low = <act_user_tag> high = ''  ) TO ranged_actual_user_tags.
      ENDLOOP.

      "DB
      DELETE FROM ptf_var_tag_map WHERE varname = @varname AND tag IN @ranged_actual_user_tags. "deletes all tags of variant if range is initial. seems ok.


      LOOP AT tags ASSIGNING FIELD-SYMBOL(<tag>).
        APPEND VALUE #( mandt = sy-mandt tag = <tag> varname = varname ) TO updated_maps.
      ENDLOOP.

      "DB
      TRY.
          INSERT ptf_var_tag_map FROM TABLE updated_maps.
        CATCH cx_sy_open_sql_db.
          BREAK griesec.
      ENDTRY.

    ENDIF.


  ENDMETHOD.
ENDCLASS.
