*"* use this source file for your ABAP unit test classes
CLASS lcl_Ptf_Var_Tag_Mgr_Tst DEFINITION DEFERRED.
CLASS cl_Ptf_Variant_Tag_Manager DEFINITION LOCAL FRIENDS lcl_Ptf_Var_Tag_Mgr_Tst.

CLASS lcl_Ptf_Var_Tag_Mgr_Tst DEFINITION FOR TESTING
  DURATION SHORT
  RISK LEVEL HARMLESS
.
*?﻿<asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
*?<asx:values>
*?<TESTCLASS_OPTIONS>
*?<TEST_CLASS>lcl_Ptf_Var_Tag_Mgr_Tst
*?</TEST_CLASS>
*?<TEST_MEMBER>f_Cut
*?</TEST_MEMBER>
*?<OBJECT_UNDER_TEST>CL_PTF_VARIANT_TAG_MANAGER
*?</OBJECT_UNDER_TEST>
*?<OBJECT_IS_LOCAL/>
*?<GENERATE_FIXTURE>X
*?</GENERATE_FIXTURE>
*?<GENERATE_CLASS_FIXTURE>X
*?</GENERATE_CLASS_FIXTURE>
*?<GENERATE_INVOCATION>X
*?</GENERATE_INVOCATION>
*?<GENERATE_ASSERT_EQUAL>X
*?</GENERATE_ASSERT_EQUAL>
*?</TESTCLASS_OPTIONS>
*?</asx:values>
*?</asx:abap>
  PRIVATE SECTION.

    CLASS-DATA environment TYPE REF TO if_osql_test_environment.

    CLASS-METHODS: class_Setup.
    CLASS-METHODS: class_Teardown.
    METHODS: setup.
    METHODS: teardown.
    METHODS: convert_User_Name FOR TESTING.
    METHODS: delete_Maps_For_Tags FOR TESTING.
    METHODS: delete_Tags_For_Variant FOR TESTING.
    METHODS: get_Editable_Tags_For_User FOR TESTING.
    METHODS: get_Variant_For_Tags FOR TESTING.
    METHODS: is_Admin FOR TESTING.
    METHODS: read_Tagged_Variants_For_User FOR TESTING.
    METHODS: set_Autogenerated_Data_For_Tag FOR TESTING.
    METHODS: transport_Ptf_Variant_Tags FOR TESTING.
    METHODS: transport_Ptf_Var_Tag_Maps FOR TESTING.
ENDCLASS.       "lcl_Ptf_Var_Tag_Mgr_Tst


CLASS lcl_Ptf_Var_Tag_Mgr_Tst IMPLEMENTATION.

  METHOD class_Setup.

    environment = cl_osql_test_environment=>create(
     i_dependency_list = VALUE #( ( 'PTF_VAR_TAG' ) ( 'PTF_VAR_TAGT' ) ( 'PTF_VAR_TAG_MAP' ) ( 'PTF_VARID' ) ) ).

  ENDMETHOD.


  METHOD class_Teardown.

    environment->destroy( ).

  ENDMETHOD.


  METHOD setup.

    environment->clear_doubles( ).

  ENDMETHOD.


  METHOD teardown.



  ENDMETHOD.


  METHOD convert_User_Name.

    DATA(pers_num_dao) = NEW lcl_pers_num_test_dao_impl( ).

    cl_ptf_variant_tag_manager=>pers_number_dao = pers_num_dao.

    pers_num_dao->pers_number_to_return = 'D072204'.

    DATA(actual_value) = cl_ptf_variant_tag_manager=>convert_user_name( user = 'ItsMe:-)' ).

    cl_abap_unit_assert=>assert_equals(
      act = actual_value
      exp = '_SAPD072204' ).


    pers_num_dao->pers_number_to_return = ''.

    actual_value = cl_ptf_variant_tag_manager=>convert_user_name( user = 'OHRM' ).

    cl_abap_unit_assert=>assert_equals(
      act = actual_value
      exp = '_SAPOHRM' ).

  ENDMETHOD.


  METHOD delete_Maps_For_Tags.
    DATA: tags                TYPE STANDARD TABLE OF ptf_var_tag,
          variants            TYPE STANDARD TABLE OF ptf_varid,
          tag_maps            TYPE STANDARD TABLE OF ptf_var_tag_map,
          input_tags          TYPE cl_ptf_variant_tag_manager=>ptf_tags,
          expected_db_content TYPE STANDARD TABLE OF ptf_var_tag_map.


    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'ABC' ) TO expected_db_content.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'GHI' ) TO expected_db_content.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'JKL' ) TO expected_db_content.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#3' varname = 'GHI' ) TO expected_db_content.


    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' visibility = 'PUBLIC' creationdat = '20200420' creator = 'AlexaBliss' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2' visibility = 'PUBLIC' creationdat = '20200420' creator = 'BeckyLynch' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#3' visibility = 'PUBLIC' creationdat = '20200420' creator = 'SashaBanks' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#4' visibility = 'PUBLIC' creationdat = '20200420' creator = 'CharlotteFlair' ) TO tags.

    APPEND VALUE #( mandt = sy-mandt varname = 'ABC' ) TO variants.
    APPEND VALUE #( mandt = sy-mandt varname = 'DEF' ) TO variants.
    APPEND VALUE #( mandt = sy-mandt varname = 'GHI' ) TO variants.
    APPEND VALUE #( mandt = sy-mandt varname = 'JKL' ) TO variants.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'ABC' ) TO tag_maps.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'GHI' ) TO tag_maps.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'JKL' ) TO tag_maps.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2' varname = 'DEF' ) TO tag_maps.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2' varname = 'JKL' ) TO tag_maps.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#3' varname = 'GHI' ) TO tag_maps.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#4' varname = 'ABC' ) TO tag_maps.


    environment->insert_test_data(
      EXPORTING
        i_data             = tags
    ).

    environment->insert_test_data(
      EXPORTING
        i_data             = variants
    ).

    environment->insert_test_data(
      EXPORTING
        i_data             = tag_maps
    ).


    APPEND 'TAG#2' TO input_tags.
    APPEND 'TAG#4' TO input_tags.

    cl_ptf_variant_tag_manager=>delete_maps_for_tags( tags = input_tags ).

    SELECT * FROM ptf_var_tag_map ORDER BY tag, varname ASCENDING INTO TABLE @DATA(actual_db_content).

    cl_abap_unit_assert=>assert_equals(
      act = actual_db_content
      exp = expected_db_content ).


    CLEAR input_tags.

    cl_ptf_variant_tag_manager=>delete_maps_for_tags( tags = input_tags ).




  ENDMETHOD.


  METHOD delete_Tags_For_Variant.
    DATA: tags                TYPE STANDARD TABLE OF ptf_var_tag,
          variants            TYPE STANDARD TABLE OF ptf_varid,
          tag_maps            TYPE STANDARD TABLE OF ptf_var_tag_map,
          expected_db_content TYPE STANDARD TABLE OF ptf_var_tag_map.


    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'ABC' ) TO expected_db_content.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'JKL' ) TO expected_db_content.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2' varname = 'DEF' ) TO expected_db_content.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2' varname = 'JKL' ) TO expected_db_content.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#4' varname = 'ABC' ) TO expected_db_content.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' visibility = 'PUBLIC' creationdat = '20200420' creator = 'AlexaBliss' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2' visibility = 'PUBLIC' creationdat = '20200420' creator = 'BeckyLynch' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#3' visibility = 'PUBLIC' creationdat = '20200420' creator = 'SashaBanks' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#4' visibility = 'PUBLIC' creationdat = '20200420' creator = 'CharlotteFlair' ) TO tags.

    APPEND VALUE #( mandt = sy-mandt varname = 'ABC' ) TO variants.
    APPEND VALUE #( mandt = sy-mandt varname = 'DEF' ) TO variants.
    APPEND VALUE #( mandt = sy-mandt varname = 'GHI' ) TO variants.
    APPEND VALUE #( mandt = sy-mandt varname = 'JKL' ) TO variants.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'ABC' ) TO tag_maps.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'GHI' ) TO tag_maps.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'JKL' ) TO tag_maps.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2' varname = 'DEF' ) TO tag_maps.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2' varname = 'JKL' ) TO tag_maps.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#3' varname = 'GHI' ) TO tag_maps.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#4' varname = 'ABC' ) TO tag_maps.


    environment->insert_test_data(
      EXPORTING
        i_data             = tags
    ).

    environment->insert_test_data(
      EXPORTING
        i_data             = variants
    ).

    environment->insert_test_data(
      EXPORTING
        i_data             = tag_maps
    ).

    cl_ptf_variant_tag_manager=>delete_tags_for_variant( variant = 'GHI' ).

    SELECT * FROM ptf_var_tag_map ORDER BY tag, varname ASCENDING INTO TABLE @DATA(actual_db_content).

    cl_abap_unit_assert=>assert_equals(
      act = actual_db_content
      exp = expected_db_content ).


  ENDMETHOD.


  METHOD get_Editable_Tags_For_User.
    DATA: tags                         TYPE STANDARD TABLE OF ptf_var_tag,
          tagts                        TYPE STANDARD TABLE OF ptf_var_tagt,
          variants                     TYPE STANDARD TABLE OF ptf_varid,
          tag_maps                     TYPE STANDARD TABLE OF ptf_var_tag_map,
          exp_bliss_tags_german        TYPE cl_ptf_variant_tag_manager=>ptf_vtags,
          exp_bliss_tags_english       TYPE cl_ptf_variant_tag_manager=>ptf_vtags,
          exp_wwe_fan_boy_tags_english TYPE cl_ptf_variant_tag_manager=>ptf_vtags.

    APPEND VALUE #( mandt = '' tag = 'TAG#1' visibility = 'PUBLIC' text = 'Das ist ein Test' creationdat = '20200420' creator = '_SAPBliss'  ) TO exp_bliss_tags_german.
    APPEND VALUE #( mandt = '' tag = 'TAG#1PRIVATE' visibility = 'PRIVATE' text = '' creationdat = '20200420' creator = '_SAPBliss'  ) TO exp_bliss_tags_german.
    APPEND VALUE #( mandt = '' tag = 'TAG#2' visibility = 'PUBLIC' text = '' creationdat = '20200420' creator = '_SAPLynch'  ) TO exp_bliss_tags_german.
    APPEND VALUE #( mandt = '' tag = 'TAG#3' visibility = 'PUBLIC' text = '' creationdat = '20200420' creator = '_SAPBanks'  ) TO exp_bliss_tags_german.
    APPEND VALUE #( mandt = '' tag = 'TAG#4' visibility = 'PUBLIC' text = '' creationdat = '20200420' creator = '_SAPFlair'  ) TO exp_bliss_tags_german.
    APPEND VALUE #( mandt = '' tag = 'TAG#5' visibility = 'PUBLIC' text = 'Das ist ein Test' creationdat = '20200420' creator = '_SAPWWEFan'  ) TO exp_bliss_tags_german.

    APPEND VALUE #( mandt = '' tag = 'TAG#1' visibility = 'PUBLIC' text = 'This is a test' creationdat = '20200420' creator = '_SAPBliss'  ) TO exp_bliss_tags_english.
    APPEND VALUE #( mandt = '' tag = 'TAG#1PRIVATE' visibility = 'PRIVATE' text = '' creationdat = '20200420' creator = '_SAPBliss'  ) TO exp_bliss_tags_english.
    APPEND VALUE #( mandt = '' tag = 'TAG#2' visibility = 'PUBLIC' text = '' creationdat = '20200420' creator = '_SAPLynch'  ) TO exp_bliss_tags_english.
    APPEND VALUE #( mandt = '' tag = 'TAG#3' visibility = 'PUBLIC' text = '' creationdat = '20200420' creator = '_SAPBanks'  ) TO exp_bliss_tags_english.
    APPEND VALUE #( mandt = '' tag = 'TAG#4' visibility = 'PUBLIC' text = '' creationdat = '20200420' creator = '_SAPFlair'  ) TO exp_bliss_tags_english.
    APPEND VALUE #( mandt = '' tag = 'TAG#5' visibility = 'PUBLIC' text = '' creationdat = '20200420' creator = '_SAPWWEFan'  ) TO exp_bliss_tags_english.

    APPEND VALUE #( mandt = '' tag = 'TAG#1' visibility = 'PUBLIC' text = 'This is a test' creationdat = '20200420' creator = '_SAPBliss'  ) TO exp_wwe_fan_boy_tags_english.
    APPEND VALUE #( mandt = '' tag = 'TAG#2' visibility = 'PUBLIC' text = '' creationdat = '20200420' creator = '_SAPLynch'  ) TO exp_wwe_fan_boy_tags_english.
    APPEND VALUE #( mandt = '' tag = 'TAG#3' visibility = 'PUBLIC' text = '' creationdat = '20200420' creator = '_SAPBanks'  ) TO exp_wwe_fan_boy_tags_english.
    APPEND VALUE #( mandt = '' tag = 'TAG#4' visibility = 'PUBLIC' text = '' creationdat = '20200420' creator = '_SAPFlair'  ) TO exp_wwe_fan_boy_tags_english.
    APPEND VALUE #( mandt = '' tag = 'TAG#5' visibility = 'PUBLIC' text = '' creationdat = '20200420' creator = '_SAPWWEFan'  ) TO exp_wwe_fan_boy_tags_english.
    APPEND VALUE #( mandt = '' tag = 'TAG#5PRIVATE' visibility = 'PRIVATE' text = '' creationdat = '20200420' creator = '_SAPWWEFan'  ) TO exp_wwe_fan_boy_tags_english.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' visibility = 'PUBLIC' creationdat = '20200420' creator = '_SAPBliss' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1PRIVATE' visibility = 'PRIVATE' creationdat = '20200420' creator = '_SAPBliss' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2' visibility = 'PUBLIC' creationdat = '20200420' creator = '_SAPLynch' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2PRIVATE' visibility = 'PRIVATE' creationdat = '20200420' creator = '_SAPLynch' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#3' visibility = 'PUBLIC' creationdat = '20200420' creator = '_SAPBanks' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#3PRIVATE' visibility = 'PRIVATE' creationdat = '20200420' creator = '_SAPBanks' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#4' visibility = 'PUBLIC' creationdat = '20200420' creator = '_SAPFlair' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#4PRIVATE' visibility = 'PRIVATE' creationdat = '20200420' creator = '_SAPFlair' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#5' visibility = 'PUBLIC' creationdat = '20200420' creator = '_SAPWWEFan' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#5PRIVATE' visibility = 'PRIVATE' creationdat = '20200420' creator = '_SAPWWEFan' ) TO tags.

    APPEND VALUE #( mandt = sy-mandt langu = 'D' tag = 'TAG#1' text = 'Das ist ein Test') TO tagts.
    APPEND VALUE #( mandt = sy-mandt langu = 'E' tag = 'TAG#1' text = 'This is a test') TO tagts.
    APPEND VALUE #( mandt = sy-mandt langu = 'D' tag = 'TAG#5' text = 'Das ist ein Test') TO tagts.
    APPEND VALUE #( mandt = sy-mandt langu = 'D' tag = 'TAG#5PRIVATE' text = 'Das ist ein Test') TO tagts.

    APPEND VALUE #( mandt = sy-mandt varname = 'ABC' ) TO variants.
    APPEND VALUE #( mandt = sy-mandt varname = 'DEF' ) TO variants.
    APPEND VALUE #( mandt = sy-mandt varname = 'GHI' ) TO variants.
    APPEND VALUE #( mandt = sy-mandt varname = 'JKL' ) TO variants.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'ABC' ) TO tag_maps.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'GHI' ) TO tag_maps.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'JKL' ) TO tag_maps.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2' varname = 'DEF' ) TO tag_maps.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2' varname = 'JKL' ) TO tag_maps.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#3' varname = 'GHI' ) TO tag_maps.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#4' varname = 'ABC' ) TO tag_maps.


    environment->insert_test_data(
      EXPORTING
        i_data             = tags
    ).

    environment->insert_test_data(
      EXPORTING
        i_data             = tagts
    ).

    environment->insert_test_data(
      EXPORTING
        i_data             = variants
    ).

    environment->insert_test_data(
      EXPORTING
        i_data             = tag_maps
    ).

    cl_ptf_variant_tag_manager=>pers_number_dao = NEW lcl_pers_num_test_dao_impl( ).

    DATA(bliss_tags_german) = cl_ptf_variant_tag_manager=>get_editable_tags_for_user(
                        user     = 'Bliss'
                        language = 'D'
                      ).

    DATA(bliss_tags_english) = cl_ptf_variant_tag_manager=>get_editable_tags_for_user(
                        user     = 'Bliss'
                        language = 'E'
                      ).

    DATA(wwe_fan_boy_tags_english) = cl_ptf_variant_tag_manager=>get_editable_tags_for_user(
                                       user     = '_SAPWWEFan'
                                       language = 'E'
                                     ).

    cl_abap_unit_assert=>assert_equals(
      act = bliss_tags_german
      exp = exp_bliss_tags_german ).

    cl_abap_unit_assert=>assert_equals(
      act = bliss_tags_english
      exp = exp_bliss_tags_english ).

    cl_abap_unit_assert=>assert_equals(
      act = wwe_fan_boy_tags_english
      exp = exp_wwe_fan_boy_tags_english ).

  ENDMETHOD.


  METHOD get_Variant_For_Tags.

    DATA: tags                  TYPE STANDARD TABLE OF ptf_var_tag,
          tagts                 TYPE STANDARD TABLE OF ptf_var_tagt,
          variants              TYPE STANDARD TABLE OF ptf_varid,
          tag_maps              TYPE STANDARD TABLE OF ptf_var_tag_map,
          tags_input            TYPE cl_ptf_variant_tag_manager=>ptf_simple_tags,
          expected_flair_output TYPE cl_ptf_variant_tag_manager=>ptf_variants,
          expected_bliss_output TYPE cl_ptf_variant_tag_manager=>ptf_variants.

    APPEND value #( mandt = sy-mandt tag = 'TAG#1' varname = 'ABC' ) TO expected_bliss_output.
    APPEND value #( mandt = sy-mandt tag = 'TAG#1' varname = 'GHI' ) TO expected_bliss_output.
    APPEND value #( mandt = sy-mandt tag = 'TAG#1' varname = 'JKL' ) TO expected_bliss_output.
    APPEND value #( mandt = sy-mandt tag = 'TAG#1PRIVATE' varname = 'MNO' ) TO expected_bliss_output.

    APPEND value #( mandt = sy-mandt tag = 'TAG#1' varname = 'ABC' ) TO expected_flair_output.
    APPEND value #( mandt = sy-mandt tag = 'TAG#1' varname = 'GHI' ) TO expected_flair_output.
    APPEND value #( mandt = sy-mandt tag = 'TAG#1' varname = 'JKL' ) TO expected_flair_output.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' visibility = 'PUBLIC' creationdat = '20200420' creator = '_SAPBliss' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1PRIVATE' visibility = 'PRIVATE' creationdat = '20200420' creator = '_SAPBliss' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2' visibility = 'PUBLIC' creationdat = '20200420' creator = '_SAPLynch' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2PRIVATE' visibility = 'PRIVATE' creationdat = '20200420' creator = '_SAPLynch' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#3' visibility = 'PUBLIC' creationdat = '20200420' creator = '_SAPBanks' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#3PRIVATE' visibility = 'PRIVATE' creationdat = '20200420' creator = '_SAPBanks' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#4' visibility = 'PUBLIC' creationdat = '20200420' creator = '_SAPFlair' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#4PRIVATE' visibility = 'PRIVATE' creationdat = '20200420' creator = '_SAPFlair' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#5' visibility = 'PUBLIC' creationdat = '20200420' creator = '_SAPWWEFan' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#5PRIVATE' visibility = 'PRIVATE' creationdat = '20200420' creator = '_SAPWWEFan' ) TO tags.

    APPEND VALUE #( mandt = sy-mandt langu = 'D' tag = 'TAG#1' text = 'Das ist ein Test') TO tagts.
    APPEND VALUE #( mandt = sy-mandt langu = 'E' tag = 'TAG#1' text = 'This is a test') TO tagts.
    APPEND VALUE #( mandt = sy-mandt langu = 'D' tag = 'TAG#5' text = 'Das ist ein Test') TO tagts.
    APPEND VALUE #( mandt = sy-mandt langu = 'D' tag = 'TAG#5PRIVATE' text = 'Das ist ein Test') TO tagts.

    APPEND VALUE #( mandt = sy-mandt varname = 'ABC' ) TO variants.
    APPEND VALUE #( mandt = sy-mandt varname = 'DEF' ) TO variants.
    APPEND VALUE #( mandt = sy-mandt varname = 'GHI' ) TO variants.
    APPEND VALUE #( mandt = sy-mandt varname = 'JKL' ) TO variants.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'ABC' ) TO tag_maps.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'GHI' ) TO tag_maps.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'JKL' ) TO tag_maps.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1PRIVATE' varname = 'MNO' ) TO tag_maps.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2' varname = 'DEF' ) TO tag_maps.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2' varname = 'JKL' ) TO tag_maps.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#3' varname = 'GHI' ) TO tag_maps.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#4' varname = 'ABC' ) TO tag_maps.


    environment->insert_test_data(
      EXPORTING
        i_data             = tags
    ).

    environment->insert_test_data(
      EXPORTING
        i_data             = tagts
    ).

    environment->insert_test_data(
      EXPORTING
        i_data             = variants
    ).

    environment->insert_test_data(
      EXPORTING
        i_data             = tag_maps
    ).

    cl_ptf_variant_tag_manager=>pers_number_dao = NEW lcl_pers_num_test_dao_impl( ).


    CLEAR tags_input.
    APPEND 'TAG#1' TO tags_input.
    APPEND 'TAG#1PRIVATE' TO tags_input.

    DATA(actual_bliss_output) = cl_ptf_variant_tag_manager=>get_variant_for_tags(
      EXPORTING
        tags     = tags_input
        user     = 'Bliss'
    ).

    DATA(actual_flair_output) = cl_ptf_variant_tag_manager=>get_variant_for_tags(
      EXPORTING
        tags     = tags_input
        user     = 'Flair'
    ).


    cl_abap_unit_assert=>assert_equals(
      act = actual_bliss_output
      exp = expected_bliss_output ).

    cl_abap_unit_assert=>assert_equals(
      act = actual_flair_output
      exp = expected_flair_output ).

  ENDMETHOD.


  METHOD is_Admin.
    DATA(pers_num_dao) = NEW lcl_pers_num_test_dao_impl( ).
    cl_ptf_variant_tag_manager=>pers_number_dao = pers_num_dao.

    pers_num_dao->pers_number_to_return = 'D021185'.

    cl_abap_unit_assert=>assert_equals(
      act = cl_ptf_variant_tag_manager=>is_admin( user = 'PODHAJSKY' )
      exp = abap_true ).

    pers_num_dao->pers_number_to_return = 'D040401'.

    cl_abap_unit_assert=>assert_equals(
      act = cl_ptf_variant_tag_manager=>is_admin( user = 'KRENZER' )
      exp = abap_true ).

    pers_num_dao->pers_number_to_return = 'D049099'.

    cl_abap_unit_assert=>assert_equals(
      act = cl_ptf_variant_tag_manager=>is_admin( user = 'GRIESEC' )
      exp = abap_true ).

    pers_num_dao->pers_number_to_return = 'D072204'.

    cl_abap_unit_assert=>assert_equals(
      act = cl_ptf_variant_tag_manager=>is_admin( user = 'OHRM' )
      exp = abap_true ).

    pers_num_dao->pers_number_to_return = 'I041586'.

    cl_abap_unit_assert=>assert_equals(
      act = cl_ptf_variant_tag_manager=>is_admin( user = 'PBODOB' )
      exp = abap_false ).

    cl_abap_unit_assert=>assert_equals(
    act = cl_ptf_variant_tag_manager=>is_admin( user = '_SAPI041586' )
    exp = abap_false ).

    cl_abap_unit_assert=>assert_equals(
      act = cl_ptf_variant_tag_manager=>is_admin( user = '_SAPD072204' )
      exp = abap_true ).

  ENDMETHOD.


  METHOD read_Tagged_Variants_For_User.
    DATA: tags               TYPE STANDARD TABLE OF ptf_var_tag,
          tagts              TYPE STANDARD TABLE OF ptf_var_tagt,
          variants           TYPE STANDARD TABLE OF ptf_varid,
          tag_maps           TYPE STANDARD TABLE OF ptf_var_tag_map,
          exp_bliss_variants TYPE cl_ptf_variant_tag_manager=>ptf_var_tag_map_table,
          exp_flair_variants TYPE cl_ptf_variant_tag_manager=>ptf_var_tag_map_table.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'ABC' ) TO exp_bliss_variants.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'GHI' ) TO exp_bliss_variants.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'JKL' ) TO exp_bliss_variants.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1PRIVATE' varname = 'JKL' ) TO exp_bliss_variants.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2' varname = 'DEF' ) TO exp_bliss_variants.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2' varname = 'JKL' ) TO exp_bliss_variants.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#3' varname = 'GHI' ) TO exp_bliss_variants.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#4' varname = 'ABC' ) TO exp_bliss_variants.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'ABC' ) TO exp_flair_variants.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'GHI' ) TO exp_flair_variants.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'JKL' ) TO exp_flair_variants.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2' varname = 'DEF' ) TO exp_flair_variants.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2' varname = 'JKL' ) TO exp_flair_variants.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#3' varname = 'GHI' ) TO exp_flair_variants.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#4' varname = 'ABC' ) TO exp_flair_variants.


    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' visibility = 'PUBLIC' creationdat = '20200420' creator = '_SAPBliss' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1PRIVATE' visibility = 'PRIVATE' creationdat = '20200420' creator = '_SAPBliss' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2' visibility = 'PUBLIC' creationdat = '20200420' creator = '_SAPLynch' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2PRIVATE' visibility = 'PRIVATE' creationdat = '20200420' creator = '_SAPLynch' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#3' visibility = 'PUBLIC' creationdat = '20200420' creator = '_SAPBanks' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#3PRIVATE' visibility = 'PRIVATE' creationdat = '20200420' creator = '_SAPBanks' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#4' visibility = 'PUBLIC' creationdat = '20200420' creator = '_SAPFlair' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#4PRIVATE' visibility = 'PRIVATE' creationdat = '20200420' creator = '_SAPFlair' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#5' visibility = 'PUBLIC' creationdat = '20200420' creator = '_SAPWWEFan' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#5PRIVATE' visibility = 'PRIVATE' creationdat = '20200420' creator = '_SAPWWEFan' ) TO tags.

    APPEND VALUE #( mandt = sy-mandt langu = 'D' tag = 'TAG#1' text = 'Das ist ein Test') TO tagts.
    APPEND VALUE #( mandt = sy-mandt langu = 'E' tag = 'TAG#1' text = 'This is a test') TO tagts.
    APPEND VALUE #( mandt = sy-mandt langu = 'D' tag = 'TAG#5' text = 'Das ist ein Test') TO tagts.
    APPEND VALUE #( mandt = sy-mandt langu = 'D' tag = 'TAG#5PRIVATE' text = 'Das ist ein Test') TO tagts.

    APPEND VALUE #( mandt = sy-mandt varname = 'ABC' ) TO variants.
    APPEND VALUE #( mandt = sy-mandt varname = 'DEF' ) TO variants.
    APPEND VALUE #( mandt = sy-mandt varname = 'GHI' ) TO variants.
    APPEND VALUE #( mandt = sy-mandt varname = 'JKL' ) TO variants.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'ABC' ) TO tag_maps.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'GHI' ) TO tag_maps.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1' varname = 'JKL' ) TO tag_maps.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1PRIVATE' varname = 'JKL' ) TO tag_maps.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2' varname = 'DEF' ) TO tag_maps.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2' varname = 'JKL' ) TO tag_maps.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#3' varname = 'GHI' ) TO tag_maps.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#4' varname = 'ABC' ) TO tag_maps.


    environment->insert_test_data(
      EXPORTING
        i_data             = tags
    ).

    environment->insert_test_data(
      EXPORTING
        i_data             = tagts
    ).

    environment->insert_test_data(
      EXPORTING
        i_data             = variants
    ).

    environment->insert_test_data(
      EXPORTING
        i_data             = tag_maps
    ).

    DATA(pers_num_dao) = NEW lcl_pers_num_test_dao_impl( ).

    cl_ptf_variant_tag_manager=>pers_number_dao = pers_num_dao.


    DATA(act_bliss_variants) = cl_ptf_variant_tag_manager=>read_tagged_variants_for_user( user =  '_SAPBliss' ).

    pers_num_dao->pers_number_to_return = 'Flair'.

    DATA(act_flair_variants) = cl_ptf_variant_tag_manager=>read_tagged_variants_for_user( user = 'Flair' ).


    cl_abap_unit_assert=>assert_equals(
      act = act_bliss_variants
      exp = exp_bliss_variants ).

    cl_abap_unit_assert=>assert_equals(
      act = act_flair_variants
      exp = exp_flair_variants ).

  ENDMETHOD.


  METHOD set_Autogenerated_Data_For_Tag.

    DATA: ptf_tag_entry TYPE v_ptf_var_tag.

    DATA(pers_num_dao) = NEW lcl_pers_num_test_dao_impl( ).

    cl_ptf_variant_tag_manager=>pers_number_dao = pers_num_dao.

    cl_ptf_variant_tag_manager=>set_autogenerated_data_for_tag(
      EXPORTING
        date        = sy-datum
        user        = '_SAPBliss'
      CHANGING
        ptf_var_tag = ptf_tag_entry
    ).

    cl_abap_unit_assert=>assert_equals(
      act = ptf_tag_entry-creator
      exp = '_SAPBliss' ).

    cl_abap_unit_assert=>assert_equals(
      act = ptf_tag_entry-creationdat
      exp = sy-datum ).

    CLEAR ptf_tag_entry.

    pers_num_dao->pers_number_to_return = 'Flair'.

    cl_ptf_variant_tag_manager=>set_autogenerated_data_for_tag(
      EXPORTING
        date        = sy-datum
        user        = 'Flair'
      CHANGING
        ptf_var_tag = ptf_tag_entry
    ).

    cl_abap_unit_assert=>assert_equals(
      act = ptf_tag_entry-creator
      exp = '_SAPFlair' ).

    cl_abap_unit_assert=>assert_equals(
      act = ptf_tag_entry-creationdat
      exp = sy-datum ).

  ENDMETHOD.


  METHOD transport_Ptf_Variant_Tags.

    DATA: tags      TYPE cl_ptf_variant_tag_manager=>ptf_tags,
          tagts     TYPE cl_ptf_variant_tag_manager=>ptf_tag_texts,
          tag_maps  TYPE cl_ptf_variant_tag_manager=>ptf_var_tag_map_table,
          exp_e071k TYPE lif_transport_manager_dao=>tt_e071k,
          exp_ko200 TYPE lif_transport_manager_dao=>tt_ko200.

    DATA(transport_dao) = NEW lcl_trans_mgr_test_dao_impl( ).

    cl_ptf_variant_tag_manager=>transport_dao = transport_dao.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1'  visibility = 'PUBLIC' creationdat = '20200420' creator = '_SAPBliss' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'YTAG#8' visibility = 'PUBLIC' creationdat = '20200420' creator = '_SAPBliss' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'ZTAG#9' visibility = 'PUBLIC' creationdat = '20200420' creator = '_SAPBliss' ) TO tags.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#1PRIVATE' visibility = 'PRIVATE' creationdat = '20200420' creator = '_SAPBliss' ) TO tags.

    APPEND VALUE #( mandt = sy-mandt langu = 'D' tag = 'TAG#1'  text = 'Das ist ein Test') TO tagts.
    APPEND VALUE #( mandt = sy-mandt langu = 'D' tag = 'ZTAG#9' text = 'Das ist ein Negativtest') TO tagts.
    APPEND VALUE #( mandt = sy-mandt langu = 'E' tag = 'TAG#1'  text = 'This is a test') TO tagts.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2'  varname = 'DEF' ) TO tag_maps.
    APPEND VALUE #( mandt = sy-mandt tag = 'ZTAG#9' varname = 'DEF' ) TO tag_maps.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#3'  varname = 'Y333' ) TO tag_maps.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2'  varname = 'JKL' ) TO tag_maps.

    cl_ptf_variant_tag_manager=>transport_ptf_variant_tags(
      EXPORTING
        ptf_var_tags                = tags
        ptf_var_tag_texts           = tagts
        deleted_var_tag_map_entries = tag_maps
    ).


    APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' Objname = 'PTF_VAR_TAG' mastername = 'PTF_VAR_TAG' mastertype = 'TABU' tabkey = |{ sy-mandt WIDTH = 3 }{ 'TAG#1' WIDTH = 80 }|  lang = sy-langu ) TO exp_e071k.
    APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' Objname = 'PTF_VAR_TAG' mastername = 'PTF_VAR_TAG' mastertype = 'TABU' tabkey = |{ sy-mandt WIDTH = 3 }{ 'TAG#1PRIVATE' WIDTH = 80 }|  lang = sy-langu ) TO exp_e071k.
    APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' Objname = 'PTF_VAR_TAGT' mastername = 'PTF_VAR_TAGT' mastertype = 'TABU' tabkey = |{ sy-mandt WIDTH = 3 }{ 'D' WIDTH = 1 }{ 'TAG#1' WIDTH = 80 }|  lang = sy-langu ) TO exp_e071k.
    APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' Objname = 'PTF_VAR_TAGT' mastername = 'PTF_VAR_TAGT' mastertype = 'TABU' tabkey = |{ sy-mandt WIDTH = 3 }{ 'E' WIDTH = 1 }{ 'TAG#1' WIDTH = 80 }|  lang = sy-langu ) TO exp_e071k.
    APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' Objname = 'PTF_VAR_TAG_MAP' mastername = 'PTF_VAR_TAG_MAP' mastertype = 'TABU' tabkey = |{ sy-mandt WIDTH = 3 }{ 'TAG#2' WIDTH = 80 }{ 'DEF' WIDTH = 31 }|  lang = sy-langu ) TO exp_e071k.
    APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' Objname = 'PTF_VAR_TAG_MAP' mastername = 'PTF_VAR_TAG_MAP' mastertype = 'TABU' tabkey = |{ sy-mandt WIDTH = 3 }{ 'TAG#2' WIDTH = 80 }{ 'JKL' WIDTH = 31 }|  lang = sy-langu ) TO exp_e071k.

    APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' obj_name = 'PTF_VAR_TAG' objfunc = 'K' lang = sy-langu ) TO exp_ko200.
    APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' obj_name = 'PTF_VAR_TAG' objfunc = 'K' lang = sy-langu ) TO exp_ko200.
    APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' obj_name = 'PTF_VAR_TAGT' objfunc = 'K' lang = sy-langu ) TO exp_ko200.
    APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' obj_name = 'PTF_VAR_TAGT' objfunc = 'K' lang = sy-langu ) TO exp_ko200.
    APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' obj_name = 'PTF_VAR_TAG_MAP' objfunc = 'K' lang = sy-langu ) TO exp_ko200.
    APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' obj_name = 'PTF_VAR_TAG_MAP' objfunc = 'K' lang = sy-langu ) TO exp_ko200.

    cl_abap_unit_assert=>assert_equals(
      act = transport_dao->e071k
      exp = exp_e071k ).

    cl_abap_unit_assert=>assert_equals(
      act = transport_dao->ko200
      exp = exp_ko200 ).

  ENDMETHOD.


  METHOD transport_Ptf_Var_Tag_Maps.

    DATA: tag_maps  TYPE cl_ptf_variant_tag_manager=>ptf_var_tag_map_table,
          exp_e071k TYPE lif_transport_manager_dao=>tt_e071k,
          exp_ko200 TYPE lif_transport_manager_dao=>tt_ko200.

    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#4' varname = 'ABC' ) TO tag_maps.
    APPEND VALUE #( mandt = sy-mandt tag = 'YTAG#8' varname = 'DEF' ) TO tag_maps.
    APPEND VALUE #( mandt = sy-mandt tag = 'ZTAG#9' varname = 'DEF' ) TO tag_maps.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#7' varname = 'Y777' ) TO tag_maps.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2' varname = 'DEF' ) TO tag_maps.
    APPEND VALUE #( mandt = sy-mandt tag = 'TAG#2' varname = 'JKL' ) TO tag_maps.

    DATA(transport_dao) = NEW lcl_trans_mgr_test_dao_impl( ).

    cl_ptf_variant_tag_manager=>transport_dao = transport_dao.

    APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' Objname = 'PTF_VAR_TAG_MAP' mastername = 'PTF_VAR_TAG_MAP' mastertype = 'TABU' tabkey = |{ sy-mandt WIDTH = 3 }{ 'TAG#4' WIDTH = 80 }{ 'ABC' WIDTH = 31 }|  lang = sy-langu ) TO exp_e071k.
    APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' Objname = 'PTF_VAR_TAG_MAP' mastername = 'PTF_VAR_TAG_MAP' mastertype = 'TABU' tabkey = |{ sy-mandt WIDTH = 3 }{ 'TAG#2' WIDTH = 80 }{ 'DEF' WIDTH = 31 }|  lang = sy-langu ) TO exp_e071k.
    APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' Objname = 'PTF_VAR_TAG_MAP' mastername = 'PTF_VAR_TAG_MAP' mastertype = 'TABU' tabkey = |{ sy-mandt WIDTH = 3 }{ 'TAG#2' WIDTH = 80 }{ 'JKL' WIDTH = 31 }|  lang = sy-langu ) TO exp_e071k.

    APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' obj_name = 'PTF_VAR_TAG_MAP' objfunc = 'K' lang = sy-langu ) TO exp_ko200.
    APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' obj_name = 'PTF_VAR_TAG_MAP' objfunc = 'K' lang = sy-langu ) TO exp_ko200.
    APPEND VALUE #( pgmid = 'R3TR' object = 'TABU' obj_name = 'PTF_VAR_TAG_MAP' objfunc = 'K' lang = sy-langu ) TO exp_ko200.

    cl_ptf_variant_tag_manager=>transport_ptf_var_tag_maps( ptf_var_tag_maps = tag_maps ).

    cl_abap_unit_assert=>assert_equals(
      act = transport_dao->e071k
      exp = exp_e071k ).

    cl_abap_unit_assert=>assert_equals(
      act = transport_dao->ko200
      exp = exp_ko200 ).

  ENDMETHOD.




ENDCLASS.
