*&---------------------------------------------------------------------*
*& Include          PROCESS_TEST_FRAMEWORK_SEL_SCR
*&---------------------------------------------------------------------*

TYPE-POOLS: icon.

CONSTANTS: lc_ecattdefault_varid TYPE etvar_id VALUE 'ECATTDEFAULT'.
CONSTANTS: lc_bofield(4)   TYPE c VALUE 'P_BO',
           lc_actfield(5)  TYPE c VALUE 'P_ACT',
           lc_testfield(6) TYPE c VALUE 'P_TEST'.

DATA: ls_step_data   TYPE cl_ptf_util=>gt_ptf_step,
      lt_step_data   TYPE TABLE OF cl_ptf_util=>gt_ptf_step,
      lt_return      TYPE cl_ptf_util=>gt_ptf_return_tab,
      ls_return      TYPE LINE OF cl_ptf_util=>gt_ptf_return_tab,
      gv_step        TYPE i VALUE 1,
      lt_data_delete TYPE TABLE OF cl_ptf_util=>gt_ptf_step,
      lv_action      TYPE ptf_act.
DATA  lt_ref_bo      TYPE cl_ptf_util=>gty_char_table.

CONSTANTS: lc_delete        TYPE ptf_act VALUE 'DELETE',
           lc_check         TYPE ptf_act VALUE 'CHECK',
           lc_create        TYPE ptf_act VALUE 'CREATE',
           lc_change        TYPE ptf_act VALUE 'CHANGE',
           lc_execute       TYPE ptf_act VALUE 'EXECUTE_ACTION',
           lc_execute_check TYPE ptf_act VALUE 'EXECUTE_CHECK',
           lc_prefix_class  TYPE ptf_act VALUE 'CL_PTF_BO_',
           lc_prefix_method TYPE ptf_act VALUE 'IF_PTF_BO~'.

DATA: dynpro_values TYPE TABLE OF dynpread,
      field_value   LIKE LINE OF dynpro_values,
      lv_suffix(2)  TYPE c.

DATA lt_exclude TYPE TABLE OF rsexfcode.

DATA: lv_ecatt_comment TYPE string,
      lt_ecatt_log type cl_ptf_wrapper=>tt_ptf_log,
      ls_ecatt_log type cl_ptf_wrapper=>ty_ptf_log,
      lv_log_rcode TYPE sysubrc.


TYPES: BEGIN OF ty_f4help,
         bo    TYPE ptfboa-ptf_bo,
         act   TYPE ptfboa-ptf_act,
         varid TYPE ectd_data-varid,
         desc  TYPE ectd_text_n-pdesc,
       END OF ty_f4help.

DATA: lv_ptf_tdcp    TYPE etp_name,
      lv_ptf_tdc     TYPE etobj_name,
      lt_ectd_data   TYPE TABLE OF ectd_data,
      lt_ptfboa      TYPE TABLE OF ptfboa,
      ls_f4help      TYPE ty_f4help,
      lt_f4help      TYPE TABLE OF ty_f4help,
      ls_ectd_text_n TYPE ectd_text_n.

FIELD-SYMBOLS: <ls_ectd_data> TYPE ectd_data,
               <ls_ptfboa>    TYPE ptfboa.



SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE TEXT-005.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-001 FOR FIELD p_bo1.
PARAMETERS p_bo1 TYPE ptfbo-ptf_bo.
SELECTION-SCREEN COMMENT 60(20) TEXT-002 FOR FIELD p_act1.
PARAMETERS p_act1 TYPE ptfboa-ptf_act..
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-003 FOR FIELD p_test1.
PARAMETERS p_test1 TYPE ptf_tdcv VALUE CHECK.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-020.
SELECTION-SCREEN COMMENT 22(18) lv_ordn.
SELECTION-SCREEN POSITION 79.
SELECTION-SCREEN COMMENT (5) icon1.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK b1.


SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME TITLE TEXT-006.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-001 FOR FIELD p_bo2.
PARAMETERS p_bo2 TYPE ptfbo-ptf_bo." OBLIGATORY VALUE CHECK.
SELECTION-SCREEN COMMENT 60(20) TEXT-002 FOR FIELD p_act2.
PARAMETERS p_act2 TYPE ptfboa-ptf_act." OBLIGATORY VALUE CHECK.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-003 FOR FIELD p_test2.
PARAMETERS p_test2 TYPE ptf_tdcv VALUE CHECK.
SELECTION-SCREEN COMMENT 60(20) TEXT-016 FOR FIELD p_vo_bo2.
PARAMETERS p_vo_bo2 TYPE ptf_ref_step.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-020.
SELECTION-SCREEN COMMENT 22(18) lv_ordn1.
SELECTION-SCREEN POSITION 79.
SELECTION-SCREEN COMMENT (5) icon2.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK b2.

SELECTION-SCREEN BEGIN OF BLOCK b3 WITH FRAME TITLE TEXT-007.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-001 FOR FIELD p_bo3.
PARAMETERS p_bo3 TYPE ptfbo-ptf_bo." OBLIGATORY VALUE CHECK.
SELECTION-SCREEN COMMENT 60(20) TEXT-002 FOR FIELD p_act3.
PARAMETERS p_act3 TYPE ptfboa-ptf_act." OBLIGATORY VALUE CHECK.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-003 FOR FIELD p_test3.
PARAMETERS p_test3 TYPE ptf_tdcv VALUE CHECK.
SELECTION-SCREEN COMMENT 60(20) TEXT-016 FOR FIELD p_vo_bo3.
PARAMETERS p_vo_bo3 TYPE ptf_ref_step.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-020.
SELECTION-SCREEN COMMENT 22(18) lv_ordn2.
SELECTION-SCREEN COMMENT 79(20) icon3.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK b3.

SELECTION-SCREEN BEGIN OF BLOCK b4 WITH FRAME TITLE TEXT-008.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-001 FOR FIELD p_bo4.
PARAMETERS p_bo4 TYPE ptfbo-ptf_bo." OBLIGATORY VALUE CHECK.
SELECTION-SCREEN COMMENT 60(20) TEXT-002 FOR FIELD p_act4.
PARAMETERS p_act4 TYPE ptfboa-ptf_act." OBLIGATORY VALUE CHECK.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-003 FOR FIELD p_test4.
PARAMETERS p_test4 TYPE ptf_tdcv VALUE CHECK.
SELECTION-SCREEN COMMENT 60(20) TEXT-016 FOR FIELD p_vo_bo4.
PARAMETERS p_vo_bo4 TYPE ptf_ref_step.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-020.
SELECTION-SCREEN COMMENT 22(18) lv_ordn3.
SELECTION-SCREEN COMMENT 79(5) icon4.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK b4.

SELECTION-SCREEN BEGIN OF BLOCK b5 WITH FRAME TITLE TEXT-009.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-001 FOR FIELD p_bo5.
PARAMETERS p_bo5 TYPE ptfbo-ptf_bo." OBLIGATORY VALUE CHECK.
SELECTION-SCREEN COMMENT 60(20) TEXT-002 FOR FIELD p_act5.
PARAMETERS p_act5 TYPE ptfboa-ptf_act." OBLIGATORY VALUE CHECK.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-003 FOR FIELD p_test5.
PARAMETERS p_test5 TYPE ptf_tdcv VALUE CHECK.
SELECTION-SCREEN COMMENT 60(20) TEXT-016 FOR FIELD p_vo_bo5.
PARAMETERS p_vo_bo5 TYPE ptf_ref_step.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-020.
SELECTION-SCREEN COMMENT 22(18) lv_ordn4.
SELECTION-SCREEN COMMENT 79(20) icon5.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK b5.

SELECTION-SCREEN BEGIN OF BLOCK b6 WITH FRAME TITLE TEXT-010.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-001 FOR FIELD p_bo6.
PARAMETERS p_bo6 TYPE ptfbo-ptf_bo." OBLIGATORY VALUE CHECK.
SELECTION-SCREEN COMMENT 60(20) TEXT-002 FOR FIELD p_act6.
PARAMETERS p_act6 TYPE ptfboa-ptf_act." OBLIGATORY VALUE CHECK.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-003 FOR FIELD p_test6.
PARAMETERS p_test6 TYPE ptf_tdcv VALUE CHECK.
SELECTION-SCREEN COMMENT 60(20) TEXT-016 FOR FIELD p_vo_bo6.
PARAMETERS p_vo_bo6 TYPE ptf_ref_step.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-020.
SELECTION-SCREEN COMMENT 22(18) lv_ordn5.
SELECTION-SCREEN COMMENT 79(20) icon6.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK b6.

SELECTION-SCREEN BEGIN OF BLOCK b7 WITH FRAME TITLE TEXT-011.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-001 FOR FIELD p_bo7.
PARAMETERS p_bo7 TYPE ptfbo-ptf_bo." OBLIGATORY VALUE CHECK.
SELECTION-SCREEN COMMENT 60(20) TEXT-002 FOR FIELD p_act7.
PARAMETERS p_act7 TYPE ptfboa-ptf_act." OBLIGATORY VALUE CHECK.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-003 FOR FIELD p_test7.
PARAMETERS p_test7 TYPE ptf_tdcv VALUE CHECK.
SELECTION-SCREEN COMMENT 60(20) TEXT-016 FOR FIELD p_vo_bo7.
PARAMETERS p_vo_bo7 TYPE ptf_ref_step.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-020.
SELECTION-SCREEN COMMENT 22(18) lv_ordn6.
SELECTION-SCREEN COMMENT 79(20) icon7.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK b7.

SELECTION-SCREEN BEGIN OF BLOCK b8 WITH FRAME TITLE TEXT-012.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-001 FOR FIELD p_bo8.
PARAMETERS p_bo8 TYPE ptfbo-ptf_bo." OBLIGATORY VALUE CHECK.
SELECTION-SCREEN COMMENT 60(20) TEXT-002 FOR FIELD p_act8.
PARAMETERS p_act8 TYPE ptfboa-ptf_act." OBLIGATORY VALUE CHECK.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-003 FOR FIELD p_test8.
PARAMETERS p_test8 TYPE ptf_tdcv VALUE CHECK.
SELECTION-SCREEN COMMENT 60(20) TEXT-016 FOR FIELD p_vo_bo8.
PARAMETERS p_vo_bo8 TYPE ptf_ref_step.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-020.
SELECTION-SCREEN COMMENT 22(18) lv_ordn7.
SELECTION-SCREEN COMMENT 79(20) icon8.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK b8.

SELECTION-SCREEN BEGIN OF BLOCK b9 WITH FRAME TITLE TEXT-013.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-001 FOR FIELD p_bo9.
PARAMETERS p_bo9 TYPE ptfbo-ptf_bo." OBLIGATORY VALUE CHECK.
SELECTION-SCREEN COMMENT 60(20) TEXT-002 FOR FIELD p_act9.
PARAMETERS p_act9 TYPE ptfboa-ptf_act." OBLIGATORY VALUE CHECK.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-003 FOR FIELD p_test9.
PARAMETERS p_test9 TYPE ptf_tdcv VALUE CHECK.
SELECTION-SCREEN COMMENT 60(20) TEXT-016 FOR FIELD p_vo_bo9.
PARAMETERS p_vo_bo9 TYPE ptf_ref_step.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-020.
SELECTION-SCREEN COMMENT 22(18) lv_ordn8.
SELECTION-SCREEN COMMENT 79(20) icon9.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK b9.

SELECTION-SCREEN BEGIN OF BLOCK b10 WITH FRAME TITLE TEXT-014.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-001 FOR FIELD p_bo10.
PARAMETERS p_bo10 TYPE ptfbo-ptf_bo  VALUE CHECK.
SELECTION-SCREEN COMMENT 60(20) TEXT-002 FOR FIELD p_act10.
PARAMETERS p_act10 TYPE ptfboa-ptf_act VALUE CHECK.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-003 FOR FIELD p_test10.
PARAMETERS p_test10 TYPE ptf_tdcv VALUE CHECK.
SELECTION-SCREEN COMMENT 60(20) TEXT-016 FOR FIELD p_v_bo10.
PARAMETERS p_v_bo10 TYPE ptf_ref_step.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-020.
SELECTION-SCREEN COMMENT 22(18) lv_ordn9.
SELECTION-SCREEN POSITION 79.
SELECTION-SCREEN COMMENT (5) icon10.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK b10.
