*----------------------------------------------------------------------*
***INCLUDE LPTF_VARIANT_TAGF01.
*----------------------------------------------------------------------*

FORM creating_a_new_entry.

  SELECT SINGLE * FROM ptf_var_tag WHERE tag = @v_ptf_var_tag-tag INTO @DATA(entry).
  IF entry IS NOT INITIAL.
    IF entry-visibility EQ 'PUBLIC'.
      MESSAGE e048(ptf).
    ELSE.
      MESSAGE e053(ptf) WITH entry-creator .
    ENDIF.
  ENDIF.

  IF v_ptf_var_tag-visibility IS INITIAL.
    MESSAGE e050(ptf).
  ENDIF.

*  IF v_ptf_var_tag-visibility EQ 'PUBLIC'.
*    DATA(is_allowed) = cl_ptf_variant_tag_manager=>is_admin(
*    EXPORTING
*      user       = sy-uname
*    ).
*
*    IF is_allowed EQ abap_false.
*      MESSAGE e046(ptf).
*      RETURN.
*    ENDIF.
*
*  ENDIF.

  cl_ptf_variant_tag_manager=>set_autogenerated_data_for_tag(
    EXPORTING
      date        = sy-datum
      user        = sy-uname
    CHANGING
      ptf_var_tag = v_ptf_var_tag
  ).

ENDFORM.

FORM ptf_tag_map_read.

  DATA(filtered_content) = cl_ptf_variant_tag_manager=>read_tagged_variants_for_user( user = sy-uname ).

  MOVE-CORRESPONDING filtered_content TO total[].

  "If the structure is still initial then its a view cluster
  IF total[] IS INITIAL.
    LOOP AT filtered_content ASSIGNING FIELD-SYMBOL(<line>).
      DATA(content) = |{ sy-mandt WIDTH = 3 }{ <line>-tag WIDTH = 80 }{ <line>-varname WIDTH = 31 }|.
      APPEND content TO total[].
    ENDLOOP.

  ENDIF.

ENDFORM.

FORM read_tags_user_related.

  DATA(filtered_content) = cl_ptf_variant_tag_manager=>get_editable_tags_for_user( user = sy-uname language = sy-langu ).

  MOVE-CORRESPONDING filtered_content TO total[].

  "If the structure is still initial then its a view cluster
  IF total[] IS INITIAL.
    LOOP AT filtered_content ASSIGNING FIELD-SYMBOL(<line>).
      DATA(content) = |{ sy-mandt WIDTH = 3 }{ <line>-tag WIDTH = 80 }{ <line>-visibility WIDTH = 7 }{ <line>-text WIDTH = 80 }{ <line>-creationdat WIDTH = 8 }{ <line>-creator WIDTH = 12 }|.
      APPEND content TO total[].
    ENDLOOP.
  ENDIF.

ENDFORM.

FORM before_saving_ptf_tag_to_db.

  DATA: tags                 TYPE cl_ptf_variant_tag_manager=>ptf_tags,
        tag                  TYPE ptf_var_tag,
        tag_texts            TYPE cl_ptf_variant_tag_manager=>ptf_tag_texts,
        tagt                 TYPE ptf_var_tagt,
        map_entries_2_delete TYPE cl_ptf_variant_tag_manager=>ptf_var_tag_map_table,
        deleted_tags         TYPE cl_ptf_variant_tag_manager=>ptf_tags.

  FIELD-SYMBOLS: <action>      TYPE any,
                 <tag>         TYPE any,
                 <visibility>  TYPE any,
                 <text>        TYPE any,
                 <creationdat> TYPE any,
                 <creator>     TYPE any.

  DATA(lo_client) = NEW cl_ptf_client( ).
  IF NOT lo_client->am_i_in_main_homedevclient( ).
*  IF <system> NE 'ER9' OR <client> NE '815'.
    MESSAGE e047(ptf).
  ENDIF.

  LOOP AT total[] ASSIGNING FIELD-SYMBOL(<change>).

    CLEAR tag.
    CLEAR tagt.

    ASSIGN COMPONENT 'ACTION' OF STRUCTURE <change> TO <action>.
    ASSIGN COMPONENT 'TAG' OF STRUCTURE <change> TO <tag>.
    ASSIGN COMPONENT 'VISIBILITY' OF STRUCTURE <change> TO <visibility>.
    ASSIGN COMPONENT 'TEXT' OF STRUCTURE <change> TO <text>.
    ASSIGN COMPONENT 'CREATIONDAT' OF STRUCTURE <change> TO <creationdat>.
    ASSIGN COMPONENT 'CREATOR' OF STRUCTURE <change> TO <creator>.

    IF <action> IS NOT ASSIGNED OR
      <tag> IS NOT ASSIGNED OR
      <visibility> IS NOT ASSIGNED OR
      <text> IS NOT ASSIGNED OR
      <creationdat> IS NOT ASSIGNED OR
      <creator> IS NOT ASSIGNED.

      "View cluster case
      "3mandt 80tag 7visibility 80text 8creationdat 12creator 1action
      ASSIGN <change>+190(1) TO <action>.
      ASSIGN <change>+3(80) TO <tag>.
      ASSIGN <change>+83(7) TO <visibility>.
      ASSIGN <change>+90(80) TO <text>.
      ASSIGN <change>+170(8) TO <creationdat>.
      ASSIGN <change>+178(12) TO <creator>.
    ENDIF.

    CASE <action>.
      WHEN 'U'. "Update

        tag-mandt = sy-mandt.
        tag-tag = <tag>.
        tag-visibility = <visibility>.
        tag-creationdat = <creationdat>.
        tag-creator = <creator>.

        tagt-mandt = sy-mandt.
        tagt-tag = <tag>.
        tagt-langu = sy-langu.
        tagt-text = <text>.

        APPEND tag TO tags.
        APPEND tagt TO tag_texts.

      WHEN 'D'. "Delete

        SELECT * FROM ptf_var_tag WHERE tag = @<tag> INTO TABLE @DATA(deleted_tags_tmp).
        SELECT * FROM ptf_var_tagt WHERE tag = @<tag> INTO TABLE @DATA(deleted_tagts).

        APPEND LINES OF deleted_tags_tmp TO tags.
        APPEND LINES OF deleted_tagts TO tag_texts.

        SELECT * FROM ptf_var_tag_map WHERE tag = @<tag> INTO TABLE @DATA(map_entries_4_tag).
        APPEND LINES OF map_entries_4_tag TO map_entries_2_delete.

        APPEND <tag> TO deleted_tags.


      WHEN 'N'. "New

        tag-mandt = sy-mandt.
        tag-tag = <tag>.
        tag-visibility = <visibility>.
        tag-creationdat = <creationdat>.
        tag-creator = <creator>.

        tagt-mandt = sy-mandt.
        tagt-tag = <tag>.
        tagt-langu = sy-langu.
        tagt-text = <text>.

        APPEND tag TO tags.
        APPEND tagt TO tag_texts.

      WHEN OTHERS.
        "No action
    ENDCASE.

    UNASSIGN <action>.
    UNASSIGN <tag>.
    UNASSIGN <visibility>.
    UNASSIGN <text>.
    UNASSIGN <creationdat>.
    UNASSIGN <creator>.

  ENDLOOP.

  cl_ptf_variant_tag_manager=>delete_maps_for_tags( tags = deleted_tags ).


  cl_ptf_variant_tag_manager=>transport_ptf_variant_tags(
    EXPORTING
      ptf_var_tags      = tags
      ptf_var_tag_texts = tag_texts
      deleted_var_tag_map_entries = map_entries_2_delete
  ).

ENDFORM.

FORM before_saving_tag_map_to_db.

  DATA: entries_to_be_transported TYPE cl_ptf_variant_tag_manager=>ptf_var_tag_map_table.

  FIELD-SYMBOLS: <action>  TYPE any,
                 <tag>     TYPE any,
                 <varname> TYPE any.

  LOOP AT total[] ASSIGNING FIELD-SYMBOL(<change>).
    ASSIGN COMPONENT 'ACTION' OF STRUCTURE <change> TO <action>.
    ASSIGN COMPONENT 'TAG' OF STRUCTURE <change> TO <tag>.
    ASSIGN COMPONENT 'VARNAME' OF STRUCTURE <change> TO <varname>.

    IF <action> IS NOT ASSIGNED OR <tag> IS NOT ASSIGNED OR <varname> IS NOT ASSIGNED.
      "View cluster case
      "3mandt 80tag 31varname 1action
      ASSIGN <change>+114(1) TO <action>.
      ASSIGN <change>+3(80) TO <tag>.
      ASSIGN <change>+83(31) TO <varname>.
    ENDIF.

    CASE <action>.

      WHEN 'N' OR 'D'.
        APPEND VALUE #( mandt = sy-mandt tag = <tag> varname = <varname> ) TO entries_to_be_transported.
      WHEN OTHERS.
    ENDCASE.

    UNASSIGN <action>.
    UNASSIGN <tag>.
    UNASSIGN <varname>.

  ENDLOOP.

  cl_ptf_variant_tag_manager=>transport_ptf_var_tag_maps( ptf_var_tag_maps = entries_to_be_transported ).

ENDFORM.

FORM tag_a_variant.
  IF v_ptf_tag_map-tag IS INITIAL OR v_ptf_tag_map-varname IS INITIAL.
    MESSAGE e049(ptf).
  ENDIF.
ENDFORM.
*&---------------------------------------------------------------------*
*& Form CREATING_A_NEW_MAPPING
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*& -->  p1        text
*& <--  p2        text
*&---------------------------------------------------------------------*
FORM creating_a_new_mapping .
  IF v_ptf_tag_map-tag IS INITIAL OR v_ptf_tag_map-varname IS INITIAL.
    MESSAGE e051(ptf).
  ENDIF.
ENDFORM.

FORM before_deleting_tag.
  FIELD-SYMBOLS: <tag>     TYPE any.

  ASSIGN total+3(80) TO <tag>.

  SELECT COUNT(*) FROM ptf_var_tag_map WHERE tag = @v_ptf_var_tag-tag INTO @DATA(tagged_variants_count).
  IF tagged_variants_count > 0.
    MESSAGE w052(ptf) WITH v_ptf_var_tag-tag tagged_variants_count .
* If you delete tag &1, &1 variants will lose a tag.
  ENDIF.

ENDFORM.
