*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: V_PTF_TAG_MAP...................................*
FORM GET_DATA_V_PTF_TAG_MAP.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM PTF_VAR_TAG_MAP WHERE
(VIM_WHERETAB) .
    CLEAR V_PTF_TAG_MAP .
V_PTF_TAG_MAP-MANDT =
PTF_VAR_TAG_MAP-MANDT .
V_PTF_TAG_MAP-TAG =
PTF_VAR_TAG_MAP-TAG .
V_PTF_TAG_MAP-VARNAME =
PTF_VAR_TAG_MAP-VARNAME .
    SELECT SINGLE * FROM PTF_VARID WHERE
VARNAME = PTF_VAR_TAG_MAP-VARNAME .
    IF SY-SUBRC EQ 0.
    ENDIF.
    SELECT SINGLE * FROM PTF_VAR_TAG WHERE
TAG = PTF_VAR_TAG_MAP-TAG .
    IF SY-SUBRC EQ 0.
    ENDIF.
<VIM_TOTAL_STRUC> = V_PTF_TAG_MAP.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_V_PTF_TAG_MAP .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO V_PTF_TAG_MAP.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_V_PTF_TAG_MAP-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM PTF_VAR_TAG_MAP WHERE
  TAG = V_PTF_TAG_MAP-TAG AND
  VARNAME = V_PTF_TAG_MAP-VARNAME .
    IF SY-SUBRC = 0.
    DELETE PTF_VAR_TAG_MAP .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM PTF_VAR_TAG_MAP WHERE
  TAG = V_PTF_TAG_MAP-TAG AND
  VARNAME = V_PTF_TAG_MAP-VARNAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR PTF_VAR_TAG_MAP.
    ENDIF.
PTF_VAR_TAG_MAP-MANDT =
V_PTF_TAG_MAP-MANDT .
PTF_VAR_TAG_MAP-TAG =
V_PTF_TAG_MAP-TAG .
PTF_VAR_TAG_MAP-VARNAME =
V_PTF_TAG_MAP-VARNAME .
    IF SY-SUBRC = 0.
    UPDATE PTF_VAR_TAG_MAP ##WARN_OK.
    ELSE.
    INSERT PTF_VAR_TAG_MAP .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_V_PTF_TAG_MAP-UPD_FLAG,
STATUS_V_PTF_TAG_MAP-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_V_PTF_TAG_MAP.
  SELECT SINGLE * FROM PTF_VAR_TAG_MAP WHERE
TAG = V_PTF_TAG_MAP-TAG AND
VARNAME = V_PTF_TAG_MAP-VARNAME .
V_PTF_TAG_MAP-MANDT =
PTF_VAR_TAG_MAP-MANDT .
V_PTF_TAG_MAP-TAG =
PTF_VAR_TAG_MAP-TAG .
V_PTF_TAG_MAP-VARNAME =
PTF_VAR_TAG_MAP-VARNAME .
    SELECT SINGLE * FROM PTF_VARID WHERE
VARNAME = PTF_VAR_TAG_MAP-VARNAME .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
    SELECT SINGLE * FROM PTF_VAR_TAG WHERE
TAG = PTF_VAR_TAG_MAP-TAG .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_V_PTF_TAG_MAP USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE V_PTF_TAG_MAP-TAG TO
PTF_VAR_TAG_MAP-TAG .
MOVE V_PTF_TAG_MAP-VARNAME TO
PTF_VAR_TAG_MAP-VARNAME .
MOVE V_PTF_TAG_MAP-MANDT TO
PTF_VAR_TAG_MAP-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'PTF_VAR_TAG_MAP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN PTF_VAR_TAG_MAP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'PTF_VAR_TAG_MAP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_V_PTF_TAG_MAP USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
PTF_VAR_TAG_MAP-MANDT =
V_PTF_TAG_MAP-MANDT .
PTF_VAR_TAG_MAP-TAG =
V_PTF_TAG_MAP-TAG .
PTF_VAR_TAG_MAP-VARNAME =
V_PTF_TAG_MAP-VARNAME .
    SELECT SINGLE * FROM PTF_VARID WHERE
VARNAME = PTF_VAR_TAG_MAP-VARNAME .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
    SELECT SINGLE * FROM PTF_VAR_TAG WHERE
TAG = PTF_VAR_TAG_MAP-TAG .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
*...processing: V_PTF_VAR_TAG...................................*
FORM GET_DATA_V_PTF_VAR_TAG.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM PTF_VAR_TAG WHERE
(VIM_WHERETAB) .
    CLEAR V_PTF_VAR_TAG .
V_PTF_VAR_TAG-MANDT =
PTF_VAR_TAG-MANDT .
V_PTF_VAR_TAG-TAG =
PTF_VAR_TAG-TAG .
V_PTF_VAR_TAG-VISIBILITY =
PTF_VAR_TAG-VISIBILITY .
V_PTF_VAR_TAG-CREATIONDAT =
PTF_VAR_TAG-CREATIONDAT .
V_PTF_VAR_TAG-CREATOR =
PTF_VAR_TAG-CREATOR .
    SELECT SINGLE * FROM PTF_VAR_TAGT WHERE
TAG = PTF_VAR_TAG-TAG AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
V_PTF_VAR_TAG-TEXT =
PTF_VAR_TAGT-TEXT .
    ENDIF.
<VIM_TOTAL_STRUC> = V_PTF_VAR_TAG.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_V_PTF_VAR_TAG .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO V_PTF_VAR_TAG.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_V_PTF_VAR_TAG-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM PTF_VAR_TAG WHERE
  TAG = V_PTF_VAR_TAG-TAG .
    IF SY-SUBRC = 0.
    DELETE PTF_VAR_TAG .
    ENDIF.
    DELETE FROM PTF_VAR_TAGT WHERE
    TAG = PTF_VAR_TAG-TAG .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM PTF_VAR_TAG WHERE
  TAG = V_PTF_VAR_TAG-TAG .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR PTF_VAR_TAG.
    ENDIF.
PTF_VAR_TAG-MANDT =
V_PTF_VAR_TAG-MANDT .
PTF_VAR_TAG-TAG =
V_PTF_VAR_TAG-TAG .
PTF_VAR_TAG-VISIBILITY =
V_PTF_VAR_TAG-VISIBILITY .
PTF_VAR_TAG-CREATIONDAT =
V_PTF_VAR_TAG-CREATIONDAT .
PTF_VAR_TAG-CREATOR =
V_PTF_VAR_TAG-CREATOR .
    IF SY-SUBRC = 0.
    UPDATE PTF_VAR_TAG ##WARN_OK.
    ELSE.
    INSERT PTF_VAR_TAG .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM PTF_VAR_TAGT WHERE
    TAG = PTF_VAR_TAG-TAG AND
    LANGU = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR PTF_VAR_TAGT.
PTF_VAR_TAGT-TAG =
PTF_VAR_TAG-TAG .
PTF_VAR_TAGT-LANGU =
SY-LANGU .
      ENDIF.
PTF_VAR_TAGT-TEXT =
V_PTF_VAR_TAG-TEXT .
    IF SY-SUBRC = 0.
    UPDATE PTF_VAR_TAGT ##WARN_OK.
    ELSE.
    INSERT PTF_VAR_TAGT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_V_PTF_VAR_TAG-UPD_FLAG,
STATUS_V_PTF_VAR_TAG-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_V_PTF_VAR_TAG.
  SELECT SINGLE * FROM PTF_VAR_TAG WHERE
TAG = V_PTF_VAR_TAG-TAG .
V_PTF_VAR_TAG-MANDT =
PTF_VAR_TAG-MANDT .
V_PTF_VAR_TAG-TAG =
PTF_VAR_TAG-TAG .
V_PTF_VAR_TAG-VISIBILITY =
PTF_VAR_TAG-VISIBILITY .
V_PTF_VAR_TAG-CREATIONDAT =
PTF_VAR_TAG-CREATIONDAT .
V_PTF_VAR_TAG-CREATOR =
PTF_VAR_TAG-CREATOR .
    SELECT SINGLE * FROM PTF_VAR_TAGT WHERE
TAG = PTF_VAR_TAG-TAG AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
V_PTF_VAR_TAG-TEXT =
PTF_VAR_TAGT-TEXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR V_PTF_VAR_TAG-TEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_V_PTF_VAR_TAG USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE V_PTF_VAR_TAG-TAG TO
PTF_VAR_TAG-TAG .
MOVE V_PTF_VAR_TAG-MANDT TO
PTF_VAR_TAG-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'PTF_VAR_TAG'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN PTF_VAR_TAG TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'PTF_VAR_TAG'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE PTF_VAR_TAG-TAG TO
PTF_VAR_TAGT-TAG .
MOVE SY-LANGU TO
PTF_VAR_TAGT-LANGU .
MOVE V_PTF_VAR_TAG-MANDT TO
PTF_VAR_TAGT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'PTF_VAR_TAGT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN PTF_VAR_TAGT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'PTF_VAR_TAGT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
