CLASS tcl_ptf_cfd_aunit_exec DEFINITION
  PUBLIC
  INHERITING FROM tcl_ptf_test_class_super
  FINAL
  CREATE PUBLIC
  FOR TESTING
  DURATION LONG
  RISK LEVEL DANGEROUS .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.

    METHODS four_ico_tests FOR TESTING .
ENDCLASS.



CLASS TCL_PTF_CFD_AUNIT_EXEC IMPLEMENTATION.


  METHOD four_ico_tests.

*    _call_named_scripts( VALUE #(
*
*( 'SDBIL_ADVC_ICO_DE_US_DLV_START' )
*( 'SDBIL_BD_ICO_W_ACC_RET_BTC' )
*( 'SDBIL_ICO_DE_US_DLV_START' )
*
*) ).

  ENDMETHOD.
ENDCLASS.
